### ISSUE TITLE
ZigguratGaussianSampler [No overload for method 'NextDouble' takes 2 arguments]

### ISSUE THREAD

**Issue by mdalvi** [colgreen/sharpneat#11]
It seems that there is some issue with Redzen 3.0.1 (updated via Nuget)

I got 
```
double ZigguratGaussianSampler.NextDouble()
No overload for method 'NextDouble' takes 2 arguments
```
**@sharpneat\src\SharpNeatLib\Network\ActivationFunctions\RadialBasis\RbfGaussian.cs**
line 123, line 136
**@sharpneat\src\SharpNeatLib\Genomes\Neat\NeatGenomeFactory.cs**
line 558

**Comment by colgreen** [comment]
I've just check in a fix. SharpNEAT 2.x should be using Redzen 2.x, so I've added a version limit to the nuget refs to prevent this occurring again. I'm not sure if Visual Studio will auto-fix itself now you have v3 installed, but just go to 'Manage Nuget Packages for solution', select RedZen and select and install version 2.0.0.

**Comment by mdalvi** [comment]
Yeah downgrading to Redzen 2.x fixed the problem. Thanks

**Comment by mdalvi** [comment]
.
