### ISSUE TITLE
MaxMinusOne - Described as Leaky ReLU?

### ISSUE THREAD

**Issue by drallensmith** [colgreen/sharpneat#17]
https://github.com/colgreen/sharpneat/blob/c5bd0bacae170930af59190a7a1b2dacf6aa80cc/src/SharpNeatLib/Network/ActivationFunctions/Unipolar/MaxMinusOne.cs#L31

I would think that should be "Shifted ReLU".

-Allen

**Comment by colgreen** [comment]
Thanks. Looks like a few are wrong due to sloppy copy/pasting. As it happens these classes have all been re-written in a refactor branch (not yet public) so I will likely close this when I merge all the changes in.

**Comment by drallensmith** [comment]
Quite welcome.

**Comment by colgreen** [comment]
I've updated all of the descriptions. As an aside, all of the name and description fields have been dropped over in [sharpneat-refactor](/colgreen/sharpneat-refactor), so this particular flavour of copy-paste bug won't be possible going forward.
