### ISSUE TITLE
You could translate this random projection AI code

### ISSUE THREAD

**Issue by S6Regen** [colgreen/sharpneat#19]
You could translate this random projection based neural network and associative memory code to C# if it happened to match your viewpoint:
https://github.com/S6Regen/EvoNet
https://randomprojectionai.blogspot.com/

**Comment by colgreen** [comment]
Does anyone have a view on what this is and how it relates to neuro-evolution and sharpneat?

**Comment by S6Regen** [comment]
You could just use the optimizer in some way:
[https://forum.processing.org/two/discussion/23422/a-simple-way-to-optimize](url)

I think to fit into how neat works a deep neural network would need to take a multidimensional input and produce a single output.  All you would have to do is sum the outputs of an n-dimension to n-dimension network.

**Comment by colgreen** [comment]
Feels like a spin-off project / investigation that would be suitable for a fork rather than an item for the core repo/project, hence am going to close this.
