### ISSUE TITLE
NuGet package of SharpNeatLib

### ISSUE THREAD

**Issue by 101100** [colgreen/sharpneat#21]
Thanks for this great project!

It would be nice to be able to include SharpNeatLib in projects using NuGet.  Currently, I must either include the source code or the library in my repository for projects that use SharpNeat.

I would appreciate the library separately because it can be used in .NET Standard 2.0 projects (thanks to your recent updates to RedZen and this project).

**Comment by colgreen** [comment]
Voilà!

https://www.nuget.org/packages/SharpNeatLib/2.4.0

**Comment by 101100** [comment]
Thanks!  I'll close the issue after giving it a try in my project (probably by Monday at the latest).

**Comment by 101100** [comment]
I've confirmed that it works in my project.  Thanks!
