### ISSUE TITLE
SharpNeatLib target .NET framework

### ISSUE THREAD

**Issue by jakesee** [colgreen/sharpneat#22]
Did the recent commit that upgraded the .NET framework to 4.7.1 break the solution? Can I get your advice please. Thank you very much.

I am getting this error framework reference warning when loading .sln file in Visual Studio 2017

Severity	Code	Description	Project	File	Line	Suppression State
Warning		Project 'D:\SVN\github\sharpneat\src\SharpNeatLib\SharpNeatLib.csproj' targets '.NETStandard,Version=v2.0'. It cannot be referenced by a project that targets '.NETFramework,Version=v4.7.1'.	SharpNeatDomains			

And I have a bunch of compile errors in SharpNeatLib:

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'ParallelOptions' could not be found (are you missing a using directive or an assembly reference?)	SharpNeatLib	D:\SVN\github\sharpneat\src\SharpNeatLib\SpeciationStrategies\ParallelKMeansClusteringStrategy.cs	38	Active

**Comment by colgreen** [comment]
I got a fresh copy of the entire repository and everything compiles fine here. The errors you are reporting suggest to me that your environment is missing some components. As a first step I would suggest running the Visual Studio Installer (just type that into the start menu search), and check you have the latest Visual Studio update (15.5.6) and also the following component (in the Summary tree view on the right hand side):

.Net Desktop Environment -> .NET Framework 4.7.1 development tools

**Comment by colgreen** [comment]
You may also need to delete temp files left over by Visual Studio from before the project file format changed, e.g. see [Upgraded from 4.6.2 to 4.7.1 and now none of my console apps will run
](https://stackoverflow.com/a/47602945/15703).

I recommend deleting the entire folder structure and re-cloning the whole. Obviously make a copy first if there is work you want to keep.

**Comment by colgreen** [comment]
Closing as this seems to be an issue with Visual Studio.
