### ISSUE TITLE
Insufficient NetworkXmlIO GetActivationFunction

### ISSUE THREAD

**Issue by DummyCo** [colgreen/sharpneat#24]
Hi there! Thank you for that amazing project.
Looks like _NetworkXmlIO.cs#L534 GetActivationFunction(string name)_ needs more registered functions such as _TanH_, _LeakyReLU_ etc to handle. Maybe it would be suitable to create single place to register all supported _IActivationFunctions_ with their aliases as some type of map?
Thank you!

**Comment by colgreen** [comment]
> Maybe it would be suitable to create single place to register all supported IActivationFunctions with their aliases as some type of map

Yes, I agree. This will be the approach in [sharpneat-refactor](/colgreen/sharpneat-refactor), for the current code base I have just updated the switch statement.

Thanks for reporting.
