### ISSUE TITLE
Multi-objective optimization?

### ISSUE THREAD

**Issue by robertvo** [colgreen/sharpneat#34]
Hi Colin,
could there be a multi fitness solution where your algorithm would minimize one variable and maximize the other? For example to maximize profits and minimize standard deviation of a trading system. I know I can lump these two into one fitness function like fitness = VAR1 * (1-VAR2), but this may now work properly. It seems there could be a more optimal way to search the space. For example your the genetic algorithm could focus on minimizing one parameter for a couple of generations and then switch to maximizing the other parameter for a couple of generations and back and forth. There could be more than 2 objectives of course.

Maybe we could re-use some code from https://github.com/chen0040/cs-moea

Could this be done? I'd pay for this add-on.

**Comment by colgreen** [comment]
Yeh looks like NSGA-II is pretty much what I was describing, although I suspect it's not useful to try and distinguish between different 'fronts' and instead just take a purely probabilistic approach of higher overall score leads to higher selection probability, but where overall score is a combination not only of the multiple objective scores, but also the density of genomes in the 2D (in my example) fitness space. (lower density => high probability of selection, i.e. there are fewer other genomes like this one, so let's increase the chances of selecting it).

Yeh you should be able to store multiple fitness scores in AuxFitnessInfo, and then use them in CreateOffSpring() when selecting genomes. This is one area in the refactor where I want to build in a bit more support in the framework for doing this sort of thing.

**Comment by robertvo** [comment]
Yeah, you're right they call this density a "Crowding Distance".  I think this selection mechanism can have a powerful impact on the overall performance.
