### ISSUE TITLE
Nuget version is older than the current latest stable version

### ISSUE THREAD

**Issue by vickylance** [colgreen/sharpneat#42]
Hi,
 
I don't know how else to contact you. So first thanks for this amazing library. But I wanted to use in my game that I am building with Godot but when I checked the latest version on nuget was older than the current stable version. So it will be helpful if you can update the same.

Thanks.

**Comment by colgreen** [comment]
Hi, I have released v2.4.4 and uploaded it to nuget.org. 

Hope that helps.

**Comment by vickylance** [comment]
@colgreen  Thank you very much
