### ISSUE TITLE
Inconsistent License Information

### ISSUE THREAD

**Issue by undecidedapollo** [colgreen/sharpneat#7]
The current license on the SharpNEAT project is indeterminable from the current repository. In the root folder of the directory, the LICENSE file states that the project is under the MIT license. In the folder containing the SLN, the COPYING file states that the project is under the GNU license. 

Since these licenses are conflicting, the project needs to specify which license is actually governing the project.

**Comment by colgreen** [comment]
Thanks for raising this.

Previously SharpNEAT was released under the GNU license and was migrated to the MIT license.

I have just now pushed an update that removes all references to the GNU license, so hopefully this is much clearer now. Please let me know if you feel further clarification is necessary.
